name: CI

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        haxe-version: [3.4.7, 4.1.5]
        os: [ubuntu-16.04, macos-10.15, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: ${{ matrix.haxe-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Linux | Install system dependencies
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev

    - name: Install Haxe dependencies
      run: |
        git clone https://github.com/haxefoundation/hxcpp
        haxelib dev hxcpp hxcpp
        cd hxcpp/tools/hxcpp
        haxe compile.hxml
        haxelib install format  --quiet
        haxelib install hxp  --quiet
        haxelib git lime-samples https://github.com/openfl/lime-samples --quiet

    - name: [Windows] Enable HXCPP compile cache
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: |
        echo "HXCPP_COMPILE_CACHE=C:\.hxcpp" >> $GITHUB_ENV

    - name: [Linux/macOS] Enable HXCPP compile cache
      if: ${{ !startsWith(matrix.os, 'windows-') }}
      run: |
        echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV

    - name: [Linux] Install Android NDK
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r15c

    - name: [Windows] Rebuild Lime tools
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: |
        haxelib dev lime $Env:GITHUB_WORKSPACE
        haxelib run lime rebuild tools -nocolor -verbose -nocffi

    - name: [Linux/macOS] Rebuild Lime tools
      if: ${{ !startsWith(matrix.os, 'windows-') }}
      run: |
        haxelib dev lime $GITHUB_WORKSPACE
        haxelib run lime rebuild tools -nocolor -verbose -nocffi

    - name: [Windows] Install "lime" command alias
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: |
        haxelib run lime setup -alias -y -nocffi

    - name: [Linux/macOS] Install "lime" command alias
      if: ${{ !startsWith(matrix.os, 'windows-') }}
      run: |
        haxelib run lime setup -alias -y -nocffi
        lime || alias lime="haxelib run lime"

    - name: [Linux] Configure Android support
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        lime config ANDROID_SDK $ANDROID_HOME
        lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
        lime config JAVA_HOME $JAVA_HOME
        lime config ANDROID_SETUP true
        lime config

    - name: Rebuild Lime (HashLink)
      run: |
        lime rebuild hl -release -verbose -nocolor

    - name: Rebuild Lime (Android)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        lime rebuild android -release -verbose -nocolor

    - name: Rebuild Lime (iOS)
      if: ${{ startsWith(matrix.os, 'macos-') }}
      run: |
        lime rebuild ios -release -verbose -nocolor

    - name: Rebuild Lime (Linux)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        lime rebuild linux -64 -release -verbose -nocolor
        lime rebuild linux -32 -release -verbose -nocolor

    - name: Rebuild Lime (macOS)
      if: ${{ startsWith(matrix.os, 'macos-') }}
      run: |
        lime rebuild mac -release -verbose -nocolor

    - name: Rebuild Lime (Windows)
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: |
        lime rebuild windows -32 -release -verbose -nocolor
        lime rebuild windows -64 -release -verbose -nocolor

    - name: Create Lime samples
      run: |
        lime create HelloWorld -verbose -nocolor
        lime create SimpleImage -verbose -nocolor
        lime create SimpleAudio -verbose -nocolor

    - name: Build Lime samples (HTML5)
      run: |
        lime build HelloWorld html5 -release -verbose -nocolor
        lime build HelloWorld html5 -Dcanvas -release -verbose -nocolor
        lime build HelloWorld html5 -Ddom -release -verbose -nocolor
        lime build SimpleImage html5 -release -verbose -nocolor
        lime build SimpleImage html5 -Dcanvas -release -verbose -nocolor
        lime build SimpleImage html5 -Ddom -release -verbose -nocolor
        lime build SimpleAudio html5 -release -verbose -nocolor
        lime build SimpleAudio html5 -Dcanvas -release -verbose -nocolor
        lime build SimpleAudio html5 -Ddom -release -verbose -nocolor

    - name: Build Lime samples (Flash)
      run: |
        lime build HelloWorld flash -release -verbose -nocolor
        lime build SimpleImage flash -release -verbose -nocolor
        lime build SimpleAudio flash -release -verbose -nocolor

    - name: Build Lime samples (Neko)
      run: |
        lime build HelloWorld neko -release -verbose -nocolor
        lime build SimpleImage neko -release -verbose -nocolor
        lime build SimpleAudio neko -release -verbose -nocolor

    #- name: Build Lime samples (HashLink)
    #  if: ${{ !startsWith(matrix.haxe-version, '3.') }}
    #  run: |
    #    lime build HelloWorld hl -release -verbose -nocolor
    #    lime build SimpleImage hl -release -verbose -nocolor
    #    lime build SimpleAudio hl -release -verbose -nocolor

    - name: Build Lime samples (Android)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        lime build HelloWorld android -release -verbose -nocolor
        lime build SimpleImage android -release -verbose -nocolor
        lime build SimpleAudio android -release -verbose -nocolor

    - name: Build Lime samples (Linux)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        lime build HelloWorld linux -release -verbose -nocolor
        lime build SimpleImage linux -release -verbose -nocolor
        lime build SimpleAudio linux -release -verbose -nocolor

    - name: Build Lime samples (macOS)
      if: ${{ startsWith(matrix.os, 'macos-') }}
      run: |
        lime build HelloWorld mac -release -verbose -nocolor
        lime build SimpleImage mac -release -verbose -nocolor
        lime build SimpleAudio mac -release -verbose -nocolor

    - name: Build Lime samples (iOS)
      if: ${{ startsWith(matrix.os, 'macos-') }}
      run: |
        lime build HelloWorld ios -simulator -release -verbose -nocolor
        lime build SimpleImage ios -simulator -release -verbose -nocolor
        lime build SimpleAudio ios -simulator -release -verbose -nocolor

    - name: Build Lime samples (Windows)
      if: ${{ startsWith(matrix.os, 'windows-') }}
      run: |
        lime build HelloWorld windows -release -verbose -nocolor
        lime build SimpleImage windows -release -verbose -nocolor
        lime build SimpleAudio windows -release -verbose -nocolor

