name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        
    - name: Setup environment
      run: |
        sudo apt-get install -y haxe libgl1-mesa-dev libglu1-mesa-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev
        #sudo apt-get install -y build-essential git curl python
        #curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
        #sudo pip install awscli awsebcli
      
    - name: Install dependencies
      run: |
        mkdir ./.haxelib
        haxelib setup ./.haxelib
        haxelib install hxcpp --quiet
        git clone https://github.com/jgranick/format ./format --depth 1
        haxelib dev format ./format
        haxelib install mcover --quiet
        haxelib install hamcrest --quiet
        git clone https://github.com/openfl/munit ./munit --depth 1
        haxelib dev munit ./munit/src
        cd ./munit/tool && haxe build.hxml
        haxelib install format --quiet
        haxelib install hxp --quiet
       
    - name: Install "lime" command alias
      run: |
        haxelib dev lime $GITHUB_WORKSPACE
        haxelib run lime setup -alias -y
        
    - name: Rebuild Lime tools
      run: |
        lime rebuild hxcpp linux -static
        lime rebuild tools -nocolor -verbose
      
    - name: Rebuild Lime binaries
      run: |
        lime rebuild linux -64 -release -verbose -nocolor
        lime rebuild linux -32 -release -verbose -nocolor
        lime rebuild android -release -verbose -nocolor
        lime rebuild hl -64 -release -verbose -nocolor
